-- PostgreSQL-compatible schema

/*
create table if not exists tb_tipo_documento(
    id int not null PRIMARY KEY auto_increment,
    tipo_documento varchar(5),
    descripcion varchar(500)
);
*/

create table if not exists tb_departamento(
    id int generated by default as identity primary key,
    nombre varchar(800)
);

create table if not exists tb_municipio(
    id int generated by default as identity primary key,
    id_departamento int not null,
    nombre varchar(800),
    estado boolean,
    foreign key (id_departamento) references tb_departamento(id)
);

create table if not exists tb_personas_club(
    id int generated by default as identity primary key,
    tipo_documento varchar(10) not null,
    numero_documento varchar(500) not null,
    id_municipio int not null,
    nombres varchar(500) not null,
    apellidos varchar(500) not null,
    fecha_nacimento date,
    tipo_rh varchar(100),
    peso double precision,
    altura double precision,
    correo varchar(500) not null,
    numero_telefono varchar(100),
    talla_camisa varchar(100),
    talla_calzado varchar(100),
    talla_pantaloneta varchar(100),
    genero varchar(200),
    direccion text,
    foreign key (id_municipio) references tb_municipio(id)
);

create table if not exists tb_usuarios(
    id int generated by default as identity primary key,
    usuario varchar(5000),
    contrasenia varchar(5000),
    activo boolean,
    id_persona int null,
    foreign key (id_persona) references tb_personas_club(id)
);

create table if not exists tb_entrenadores(
    id int generated by default as identity primary key,
    id_persona_club int not null,
    fecha_ingreso date,
    activo boolean,
    contrato bytea,
    foreign key (id_persona_club) references tb_personas_club(id)
);

create table if not exists tb_contactos_emergencia(
    id int generated by default as identity primary key,
    tipo_documento varchar(10) not null,
    numero_documento varchar(100) not null,
    id_entrenador int,
    nombres varchar(5000),
    apellidos varchar(5000),
    correo text,
    telefono text,
    foreign key (id_entrenador) references tb_entrenadores(id)
);

create table if not exists tb_tutores(
    id int generated by default as identity primary key,
    tipo_documento varchar(10) not null,
    numero_documento varchar(100) not null,
    nombres varchar(5000),
    apellidos varchar(5000),
    correo text,
    telefono text
);

create table if not exists tb_categorias(
    id varchar(100) not null primary key,
    nombre text
);

create table if not exists tb_deportistas(
    id int generated by default as identity primary key,
    id_tutor int,
    id_persona_club int not null,
    id_categoria varchar(100),
    activo boolean,
    foreign key (id_tutor) references tb_tutores(id),
    foreign key (id_persona_club) references tb_personas_club(id),
    foreign key (id_categoria) references tb_categorias(id)
);

create table if not exists tb_desercion_deportistas(
    id int generated by default as identity primary key,
    id_deportista int not null,
    fecha_desercion date,
    razon varchar(800),
    descripcion text,
    foreign key (id_deportista) references tb_deportistas(id)
);

create table if not exists tb_pagos_deportistas(
    id int generated by default as identity primary key,
    id_deportista int not null,
    fecha_pago date,
    valor numeric(10,2),
    tipo_pago text,
    foreign key (id_deportista) references tb_deportistas(id)
);

create table if not exists tb_cargos_admin(
    id int generated by default as identity primary key,
    nombre varchar(1000)
);

create table if not exists tb_gestion_admin(
    id int generated by default as identity primary key,
    id_tutor int null,
    id_deportista int null,
    id_cargo int,
    fecha_inicio date,
    fecha_fin date,
    activo boolean,
    foreign key (id_tutor) references tb_tutores(id),
    foreign key (id_deportista) references tb_deportistas(id),
    foreign key (id_cargo) references tb_cargos_admin(id)
);
