import { Injectable } from '@angular/core';
import { AthleteResponse } from '@sacd/core/http/responses';
import { DataTableApi } from '@web/libs/shared/ui/tables';
import { Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class AthleteApiService extends DataTableApi<AthleteResponse> {
  override getData(): Observable<AthleteResponse[]> {
    return of([]);
  }
}
/**
 *  return of([
      {
        id: 1,
        tipoDocumento: 1019125746,
        idMunicipio: 101,
        idUsuario: 1001,
        nombres: 'Juan',
        apellidos: 'Pérez',
        fechaNacimiento: new Date('2000-01-01'),
        tipoRh: 'O+',
        peso: 70,
        altura: 175,
        correo: 'juan.perez@example.com',
        numeroTelefono: 1234567890,
        tallaCamisa: 'M',
        tallaCalzado: '42',
        tallaPantaloneta: 'L',
        genero: 'Masculino',
        direccion: 'Calle 123 #45-67',
        idAthlete: 1,
        tutor: {
          id: 201,
          tipoDocumento: 2,
          nombres: 'Carlos',
          apellidos: 'Gómez',
          correo: 'carlos.gomez@example.com',
          telefono: '987654321',
        },
        activo: true,
        categoria: { id: 1, nombre: 'Junior' },
      },
      {
        id: 2,
        tipoDocumento: 1,
        idMunicipio: 102,
        idUsuario: 1002,
        nombres: 'María',
        apellidos: 'López',
        fechaNacimiento: new Date('1998-05-15'),
        tipoRh: 'A+',
        peso: 60,
        altura: 165,
        correo: 'maria.lopez@example.com',
        numeroTelefono: 987654321,
        tallaCamisa: 'S',
        tallaCalzado: '38',
        tallaPantaloneta: 'M',
        genero: 'Femenino',
        direccion: 'Carrera 45 #67-89',
        idAthlete: 2,
        tutor: {
          id: 202,
          tipoDocumento: 3,
          nombres: 'Ana',
          apellidos: 'Martínez',
          correo: 'ana.martinez@example.com',
          telefono: '123123123',
        },
        activo: false,
        categoria: { id: 2, nombre: 'Senior' },
      },
      {
        id: 3,
        tipoDocumento: 2,
        idMunicipio: 103,
        idUsuario: 1003,
        nombres: 'Carlos',
        apellidos: 'Hernández',
        fechaNacimiento: new Date('2002-09-10'),
        tipoRh: 'B+',
        peso: 80,
        altura: 180,
        correo: 'carlos.hernandez@example.com',
        numeroTelefono: 321321321,
        tallaCamisa: 'L',
        tallaCalzado: '44',
        tallaPantaloneta: 'XL',
        genero: 'Masculino',
        direccion: 'Avenida 10 #20-30',
        idAthlete: 3,
        tutor: {
          id: 203,
          tipoDocumento: 4,
          nombres: 'Luis',
          apellidos: 'Ramírez',
          correo: 'luis.ramirez@example.com',
          telefono: '456456456',
        },
        activo: true,
        categoria: { id: 3, nombre: 'Youth' },
      },
      {
        id: 4,
        tipoDocumento: 3,
        idMunicipio: 104,
        idUsuario: 1004,
        nombres: 'Ana',
        apellidos: 'García',
        fechaNacimiento: new Date('1995-12-25'),
        tipoRh: 'AB+',
        peso: 55,
        altura: 160,
        correo: 'ana.garcia@example.com',
        numeroTelefono: 654654654,
        tallaCamisa: 'XS',
        tallaCalzado: '36',
        tallaPantaloneta: 'S',
        genero: 'Femenino',
        direccion: 'Calle 50 #60-70',
        idAthlete: 4,
        tutor: {
          id: 204,
          tipoDocumento: 5,
          nombres: 'Pedro',
          apellidos: 'López',
          correo: 'pedro.lopez@example.com',
          telefono: '789789789',
        },
        activo: true,
        categoria: { id: 4, nombre: 'Professional' },
      },
      {
        id: 5,
        tipoDocumento: 4,
        idMunicipio: 105,
        idUsuario: 1005,
        nombres: 'Luis',
        apellidos: 'Martínez',
        fechaNacimiento: new Date('1990-07-20'),
        tipoRh: 'O-',
        peso: 85,
        altura: 185,
        correo: 'luis.martinez@example.com',
        numeroTelefono: 987987987,
        tallaCamisa: 'XL',
        tallaCalzado: '46',
        tallaPantaloneta: 'XXL',
        genero: 'Masculino',
        direccion: 'Carrera 80 #90-100',
        idAthlete: 5,
        tutor: {
          id: 205,
          tipoDocumento: 6,
          nombres: 'Sofía',
          apellidos: 'Pérez',
          correo: 'sofia.perez@example.com',
          telefono: '123987123',
        },
        activo: false,
        categoria: { id: 5, nombre: 'Amateur' },
      },
    ]);
 */
